# permissions for end users to view clusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-operator
    app.kubernetes.io/part-of: kube-operator
    app.kubernetes.io/managed-by: kustomize
  name: cluster-viewer-role
rules:
- apiGroups:
  - kubean.io.cogiot.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubean.io.cogiot.io
  resources:
  - clusters/status
  verbs:
  - get
